### PR TITLE
For working with the data after it has been downloaded

### PR DESCRIPTION
**Pull request by padpadpadpad**
I was interested in plotting a heat map of all my rides using R and have done so. Trying to make the process a bit cleaner by making a few functions convert the huge lists you get from get_activity_list() into a data frame.

Pretty new to this git and R package process so comments welcome. 

And I have created a first bash at a heat map....

[heatmap_plot.pdf](https://github.com/fawda123/rStrava/files/455164/heatmap_plot.pdf)

### CODE REVIEW

**Comment by padpadpadpad** [comment]
I am going to work on the Travis build for this first and then re-request. Alternatively I could just wrap these in another package.

**Comment by fawda123** [comment]
@padpadpadpad nice!  First time someone has actually contributed to a package of mine... I'm reopening the commit, these additions look way cool.  You can make another PR if you fix the build issues, otherwise I can take a stab at it.

**Comment by padpadpadpad** [comment]
Awesome. So I have started fiddling about with my fork again trying to get the changes to work. No luck yet but will have another bash later so might be easier to do another pull request if I get that working...

If there is another way to update this pull request let me know but Git is still pretty much a black box to me!

**Comment by fawda123** [comment]
@padpadpadpad The commits will add to the pull request as long as it's open.  Looks like you've got the checks working... I'll close the PR and will have a look at the functions.  Thanks!

**Pull request merged**
